---

name: Run ansible role
  on: 
   push:
    branches: 
     - main
  hosts: web
  tasks:
    - name: install apache
      yum:
        name: httpd 
        state: latest
    - name: start apache
      service:
        name: httpd
        state: started
        enabled: true
    - name: create index.html
      template:
        src: ~/automation/templates/roles_apache.j2
        dest: /var/www/html/index.html
      tags: index_tag
    - name: restart apache
      service:
        name: httpd
        state: restarted
      tags: index_tag
    - name: configure firewall
      firewalld:
        service: http
        immediate: yes
        permanent: yes
        state: enabled
...
